#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N myjob0
#PBS -o myjob.out
#PBS -e myjob.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M drr027@latech.edu
work="/home/drayborn/lab2"
XFILE="Lab2_1a"
cd $work
./$XFILE
